version: '3.9'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - appdemo

  nodejs:
    build: .
    depends_on:
      - mongodb
    restart: unless-stopped
    ports:
    - "3000:3000"
    networks:
      - appdemo

networks:
  appdemo:
